[package]
name = "toy-browser"
version = "0.1.0"
authors = ["Deepankar Agrawal <deepankar11093@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.22.0"
reqwest = { version = "0.10", features = ["blocking"] }
